### ISSUE TITLE
Edit // or ||

### ISSUE THREAD

**Issue by ajaniak** [arlogriffiths/Khmer-Epigraphy#1]
@arlogriffiths,

While adding the file from Kunthea, I tried to figure if you rather use // or ||. Since I still found both in the repository. I didn't make any change on the matter. However, in the files I have pushed, it is not the same signed used between the previous and the new version of K0182-I line 12, called (02) in the file.

**Comment by arlogriffiths** [comment]
In principle, both have a different meaning defined in our Transliteration guide, but since many older editions and many current scholars don't systematically make the distinction, and use // where we require ||, many of our .txt may not reflect the required transliteration either. I think in `K0182-I-fragment1.txt` we need || instead of //, but I will confirm with Kunthea.

**Comment by arlogriffiths** [comment]
Kunthea confirms and will change to II.
